ARG APP_IMAGE=fdcl-app

FROM ${APP_IMAGE} AS app

FROM nginx:alpine

RUN apk add --no-cache curl

COPY docker/nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=app /var/www/html/public /var/www/html/public

EXPOSE 80
