ARG APP_IMAGE=fdcl-app:bare-prod-local

FROM ${APP_IMAGE} AS app

FROM nginx:alpine
COPY --from=app /var/www/html/public /var/www/html/public
COPY docker/nginx/prod.conf /etc/nginx/conf.d/default.conf
