FROM node:20-alpine AS frontend

WORKDIR /app

COPY src/package*.json ./
RUN npm ci

COPY src/ .
RUN npm run build

FROM nginx:alpine

RUN apk add --no-cache curl

COPY docker/nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend /app/public/build /var/www/html/public/build

EXPOSE 80
