tls:
  certificates:
    - certFile: /certs/ahmedmusa.local.pem
      keyFile: /certs/ahmedmusa.local-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/ahmedmusa.local.pem
        keyFile: /certs/ahmedmusa.local-key.pem
